### ISSUE TITLE
Is one of the dependencies broken?

### ISSUE THREAD

**Issue by heshiming** [koajs/api-boilerplate#4]
I've been using koajs and api-boilerplate for some time now, suddenly it's broken on new installations. After cloning this repo and `npm install`, I'm seeing the following messages in `make test`

```
  GET /stats
    1) should respond with stats

  GET /stats/:name

  GET /users


  0 passing (22ms)
  1 failing

  1) GET /stats should respond with stats:
     TypeError: undefined is not a function
      at resource (/Users/user/Desktop/api-boilerplate/lib/load/index.js:72:7)
      at /Users/user/Desktop/api-boilerplate/lib/load/index.js:36:12
      at Array.forEach (native)
      at module.exports (/Users/user/Desktop/api-boilerplate/lib/load/index.js:28:17)
      at api (/Users/user/Desktop/api-boilerplate/index.js:58:3)
      at Context.<anonymous> (/Users/user/Desktop/api-boilerplate/api/stats/test.js:7:15)
      at Test.Runnable.run (/Users/user/Desktop/api-boilerplate/node_modules/mocha/lib/runnable.js:196:15)
      at Runner.runTest (/Users/user/Desktop/api-boilerplate/node_modules/mocha/lib/runner.js:373:10)
      at /Users/user/Desktop/api-boilerplate/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/user/Desktop/api-boilerplate/node_modules/mocha/lib/runner.js:298:14)
      at /Users/user/Desktop/api-boilerplate/node_modules/mocha/lib/runner.js:308:7
      at next (/Users/user/Desktop/api-boilerplate/node_modules/mocha/lib/runner.js:246:23)
      at Immediate._onImmediate (/Users/user/Desktop/api-boilerplate/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:374:17)
```

I'm seeing the exact same exception when running `node --harmony bin/api`. I'm using node v0.11.13. The exception says something about `app` variable being undefined.

Is it working for everyone else? What might be the cause of this problem?

**Comment by heshiming** [comment]
In node 0.11.12, the exception message is different, it's not `undefined is not a function`, it's `TypeError: Object #<Application> has no method 'resource'` instead. I'm positive it's a problem with dependency, but I'm not sure which.

**Comment by jonathanong** [comment]
probably `koa-router` changed

**Comment by tj** [comment]
semver ftw?
